{{- if and .Values.postgres.persistence.enabled (ne (.Values.postgres.persistence.type | default "storageClass") "hostpath") }}
{{- $storageClass := .Values.postgres.persistence.storageClass | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "station.postgresPvcName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $storageClass.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $storageClass.size }}
  {{- with $storageClass.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
