apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "station.stationConfigName" . }}
  labels:
    {{- include "station.labels" . | nindent 4 }}
data:
  config.toml: |-
{{ .Files.Get "station-config/config/config.toml" | indent 4 }}
  {{- $caCrt := .Files.Get "station-config/tls/CA.crt" }}
  {{- if $caCrt }}
  CA.crt: |-
{{ $caCrt | indent 4 }}
  {{- end }}
