replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

wparse:
  config:
    type: hostpath
    path: "/data/work"
  workDir: /data
  warpParseSecretPath: /root/.warp_parse
  command:
    - wparse
  args:
    - deamon
  service:
    type: NodePort
    ports:
      # 追加一个UDP端口
      - name: syslog      # 任意名字
        port: 1514        # source监听的端口
        protocol: UDP     # 端口协议，TCP或UDP
        nodePort: 30514   # 宿主机暴露的端口，范围30000-32767
  adminService:
    type: NodePort
    port: 19090
    nodePort: 30090
  nodeSelector:
    kubernetes.io/hostname: dayu01.shmh.dysec

# 以下是一些通用的配置项，可以根据需要进行修改
  image:
    repository: ghcr.io/wp-labs/warp-parse-exp
    pullPolicy: IfNotPresent
    tag: "exp-v0.23.6-12-alpha"
  initImage:
    repository: busybox
    pullPolicy: IfNotPresent
    tag: "1.36"
  timezone:
    enabled: true
    name: Asia/Shanghai
  envFrom: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  warpParseSecret:
    existingSecret: ""
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  httpRoute:
    enabled: false
    annotations: {}
    parentRefs:
      - name: gateway
        sectionName: http
    hostnames:
      - chart-example.local
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  tolerations: []
  affinity: {}