apiVersion: v1
kind: Service
metadata:
  name: {{ include "wparse.fullname" . }}-admin
  labels:
    {{- include "wparse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wparse.adminService.type }}
  ports:
    - name: admin
      port: {{ .Values.wparse.adminService.port }}
      targetPort: admin
      protocol: TCP
      {{- if and (eq .Values.wparse.adminService.type "NodePort") .Values.wparse.adminService.nodePort }}
      nodePort: {{ .Values.wparse.adminService.nodePort }}
      {{- end }}
  selector:
    {{- include "wparse.selectorLabels" . | nindent 4 }}
