apiVersion: v1
kind: Service
metadata:
  name: {{ include "wparse.fullname" . }}
  labels:
    {{- include "wparse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wparse.service.type }}
  ports:
    {{- range .Values.wparse.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort | default .name }}
      protocol: {{ .protocol | default "TCP" }}
      {{- if and (eq $.Values.wparse.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "wparse.selectorLabels" . | nindent 4 }}
