apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wp-monitor.componentFullname" (dict "context" . "name" "config") }}
  labels:
    {{- include "wp-monitor.labels" . | nindent 4 }}
data:
  app.toml: |
    vm_base_url = "http://{{ include "wp-monitor.componentFullname" (dict "context" . "name" "victoria-metrics") }}:{{ .Values.victoriaMetrics.service.port }}"
    vlog_base_url = "http://{{ include "wp-monitor.componentFullname" (dict "context" . "name" "victoria-logs") }}:{{ .Values.victoriaLogs.service.port }}"
    log_level = "info"
