services:
  warp-parse:
    user: "root"
    image: ghcr.io/wp-labs/warp-parse:0.23.8-alpha
    container_name: warp-parse
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "19002:19002"
      - "19090:19090"
    volumes:
      - ./wparse:/app/config
      - ./wparse/.warp_parse:/root/.warp_parse
    entrypoint: ["wparse", "deamon", "--work-root", "/app/config"]
    networks:
      - warp-network

networks:
  warp-network:
    driver: bridge